export const LOADING = "LOADING";
export const SET_CHOOSE_SERVICE_LIST = "SET_CHOOSE_SERVICE_LIST";
export const UPDATE_CHOOSE_SERVICE = "UPDATE_CHOOSE_SERVICE";
export const DELETE_CHOOSE_SERVICE = "DELETE_CHOOSE_SERVICE";
export const ADD_ORDER = "ADD_ORDER";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";
export const REMOVE_SERVICE_FROM_ORDER = "REMOVE_SERVICE_FROM_ORDER";
