export const GET_LIST_POST = "GET_LIST_POST";
export const GET_DETAIL_POST = "GET_DETAIL_POST";
export const GET_PAGINATE_POSIBILITY = "GET_PAGINATE_POSIBILITY";
export const GET_SEARCH_LIST_POST = "GET_SEARCH_LIST_POST";
