export const GET_PROMO_BY_STUDIO_POST = "GET_PROMO_BY_STUDIO_POST";
export const GET_ALL_PROMO_CODE = "GET_ALL_PROMO_CODE";
export const GET_PAGINATE_POSSIBILITY = "GET_PAGINATE_POSSIBILITY";
export const SET_STUDIO_POST_ID = "SET_STUDIO_POST_ID";
export const SET_PROMOTION_CODE_USER_SAVE = "SET_PROMOTION_CODE_USER_SAVE";
export const SET_CHOOSE_PROMOTION_USER = "SET_CHOOSE_PROMOTION_USER";
export const SAVE_PROMOTION = "SAVE_PROMOTION";
export const CANCEL_SAVE_PROMOTION = "CANCEL_SAVE_PROMOTION";
