export const GET_PROMO_BY_STUDIO_POST = "GET_PROMO_BY_STUDIO_POST";
export const GET_ALL_PROMO_CODE = "GET_ALL_PROMO_CODE";
export const GET_PAGINATE_POSSIBILITY = "GET_PAGINATE_POSSIBILITY";
export const SET_STUDIO_POST_ID = "SET_STUDIO_POST_ID";
