export const LOADING = "LOADING";
export const SET_FILTER = "SET_FILTER";
export const SET_POST_LIST = "SET_POST_LIST";
export const SET_POST_PAGINATION = "SET_POST_PAGINATION";
export const SET_STUDIO_DETAIL = "SET_STUDIO_DETAIL";
export const SET_STUDIO_DETAIL1 = "SET_STUDIO_DETAIL1";
export const SET_STUDIO_NEAR = "SET_STUDIO_NEAR";
